version: '2'
services:
  pcc.db:
    image: postgres
  pcc.web:
    build: .
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=db
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/pcc
    ports:
      - "5000:5000"
    links:
      - pcc.db:db
    depends_on:
      - pcc.db
