version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 5001 -b '0.0.0.0'
    volumes:
      - .:/merch-it
    ports:
      - "5001:5001"
    depends_on:
      - db
